export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_ERROR = "LOGIN_ERROR"

export const EDIT_USER_REQUEST = "EDIT_USER_REQUEST"
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS"
export const EDIT_USER_ERROR = "EDIT_USER_ERROR"

export const SIGNUP_REQUEST = "SIGNUP_REQUEST"
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
export const SIGNUP_ERROR = "SIGNUP_ERROR"

export const SAVE_PORTFOLIO_REQUEST = "SAVE_PORTFOLIO_REQUEST"
export const SAVE_PORTFOLIO_SUCCESS = "SAVE_PORTFOLIO_SUCCESS"
export const SAVE_PORTFOLIO_ERROR = "SAVE_PORTFOLIO_ERROR"

export const GET_PORTFOLIOS_REQUEST = "GET_PORTFOLIOS_REQUEST"
export const GET_PORTFOLIOS_SUCCESS = "GET_PORTFOLIOS_SUCCESS"
export const GET_PORTFOLIOS_ERROR = "GET_PORTFOLIOS_ERROR"

export const EDIT_ADMIN_PARAMS_REQUEST = "EDIT_ADMIN_PARAMS_REQUEST"
export const EDIT_ADMIN_PARAMS_SUCCESS = "EDIT_ADMIN_PARAMS_SUCCESS"
export const EDIT_ADMIN_PARAMS_ERROR = "EDIT_ADMIN_PARAMS_ERROR"

export const GET_ADMIN_PARAMS_REQUEST = "GET_ADMIN_PARAMS_REQUEST"
export const GET_ADMIN_PARAMS_SUCCESS = "GET_ADMIN_PARAMS_SUCCESS"
export const GET_ADMIN_PARAMS_ERROR = "GET_ADMIN_PARAMS_ERROR"

export const GET_ALL_PORTFOLIOS_REQUEST = "GET_ALL_PORTFOLIOS_REQUEST"
export const GET_ALL_PORTFOLIOS_SUCCESS = "GET_ALL_PORTFOLIOS_SUCCESS"
export const GET_ALL_PORTFOLIOS_ERROR = "GET_ALL_PORTFOLIOS_ERROR"

export const GET_ALL_USERS_REQUEST = "GET_ALL_USERS_REQUEST"
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS"
export const GET_ALL_USERS_ERROR = "GET_ALL_USERS_ERROR"

export const GET_COMPUTED_PARAMS_REQUEST = "GET_COMPUTED_PARAMS_REQUEST"
export const GET_COMPUTED_PARAMS_SUCCESS = "GET_COMPUTED_PARAMS_SUCCESS"
export const GET_COMPUTED_PARAMS_ERROR = "GET_COMPUTED_PARAMS_ERROR"